### ISSUE TITLE
Additional exploratory notebooks needed

### ISSUE THREAD

**Issue by carlosgjs** [noisepy/NoisePy#179]
I want to add 2 notebooks: 1) exploration of the data with toy problem of noisepy to find optimal configParam to run CC, 2) post-processing exploration of the data to establish more paramters for the monitoring and earth imaging applicaitons

[Slack Message](https://escience-institute.slack.com/archives/C04T1P8FP9N/p1692143366359419?thread_ts=1691626669.338409&cid=C04T1P8FP9N)

**Comment by mdenolle** [comment]
Fixed in recent PRs with new tutorials
