### ISSUE TITLE
Process 30 days on SCEDC data on AWS batch

### ISSUE THREAD

**Issue by carlosgjs** [noisepy/NoisePy#180]
@mdenolle  can you specify for me:

- The list of stations to use
- The date range to process
- Any non-default configuration parameters you'd like to use

You can then re-assign the issue to me. thx!

**Comment by mdenolle** [comment]
I am a bit confused about how to set up the CLI parameters, maybe we could spend some time updating the tutorials. Do we now pass a text file with the list of the stations as net.sta.loc ?

Using aws cli, we can create a list of the stations available for a given day. Here is my quick attempt:
`aws s3 ls s3://scedc-pds/continuous_waveforms/2023/2023_209/ > toto
awk -F" " '{print $4}' toto | cut -c1-2 > list_net
awk -F" " '{print $4}' toto | cut -c3-7 | sed  's/_/\ /g' > list_sta`
Note that i did not select for specific HH, BH, or EH channel, but we can do that in shell easily.
The name of the channels available won't change much at the month-year time scale, but they will change at the 5-year time scale.
We could combine both list_net.list_sta to pass into the CLI command, or write the filename into the config file.

Default parameters are fine.

Date range: randomly picking 
2023/2023_180 - 2023/2023_210
to be close to the station listing picked in the above line.

Let me know how it goes!

**Comment by carlosgjs** [comment]
1 month run (06/2023):
CCF: s3://scoped-noise/scedc_CI_ccf_v4  (1,189,671 files, 297GB)
STACK: s3://scoped-noise/scedc_CI_stack_v4 (42,535 files, 21.1GB)


1 Year run (2022):
CCF: s3://scoped-noise/scedc_CI_2022_ccf/ ~11.5 hrs on 64 nodes  (6.2M files, 1.6TB)
STACK: s3://scoped-noise/scedc_CI_2022_stack/  ~1.5hr on 64 nodes (46,273 files, 23GB)
config: s3://scoped-noise/configs/CI_2022.yaml
