### ISSUE TITLE
Migrate readthedocs with github pages

### ISSUE THREAD

**Issue by mdenolle** [noisepy/NoisePy#190]
Merge documentations under the same framework

Here's an example of integrating `ipynb` notebooks and `.md` files: https://github.com/OSOceanAcoustics/echopype/tree/main/docs/source

First goal is to add the `tutorials/cloud` and `tutorials/cli` to the jupyter book by adding them to `tutorials/_toc.yml`. You can test this locally by running

```
cd tutorials
pip install -r requirements.txt
jb build . -W
```

This is what the `.github/workflows/notebook.yml` workflow does during PRs and releases.

We also need update the docs badge link in the README to point to the github pages

@IshikaKhandelwal - can you:
- Rename the `docs` folder to `doc_old`
- Update all links in the README (and any others you find) from `readthedocs.org` to https://noisepy.github.io/NoisePy/
  - For the docs badge, you can point to the notebooks workflow: `https://github.com/noisepy/NoisePy/actions/workflows/notebooks.yml/badge.svg`
- Make noisepy_scedc_tutorial the `root:` in the `_toc.yml`
- Add `noise_configuration` as a file

**Comment by carlosgjs** [comment]
@mdenolle Once this is done, we probably want to take down the readthedocs page: https://noisepy.readthedocs.io/en/latest/index.html?  Anything from there we want to preserve?

**Comment by mdenolle** [comment]
we can keep the old files into a doc_old folder
