### ISSUE TITLE
Re-organize code for applications, DAS, imaging, etc...

### ISSUE THREAD

**Issue by carlosgjs** [noisepy/NoisePy#249]
Reorganize codes:

- [x] make new folder in src, src/noisepy/monitoring and move all monitoring scripts relevant there - test using a tutorial notebook to add to our tutorial collections. Namespace will be noisepy.monitoring.
- [ ] make new folder in src, src/noisepy/imaging and move all monitoring scripts relevant there - test using a tutorial notebook to add to our tutorial collections. Namespace will be noisepy.imaging.
- [x] make a new repository for namespace noisepy.das, repository noisepy4das. test for compatibility with other noisepy packages, especially noisepy.io.

**Comment by mdenolle** [comment]
Great!
Let's create
``noisepy.imaging`` and move ``dispersion_analysis.py`` in it. We may create another ``imaging_utils.py`` by adding a few functions that we moved away from ``noise_module.py``. @niyiyu .

**Comment by mdenolle** [comment]
- [ ] Develop a new ConfigMonitoringParameter class to read / store all parameters for dv/v and attenuation
