### ISSUE TITLE
Problems with tutorial

### ISSUE THREAD

**Issue by Javitsg** [noisepy/NoisePy#263]
Hello,

I'm having problems with the tutorial.
The first problem I have encountered is the following:
_ImportError: cannot import name 'CCMethod' from 'noisepy.seis.datatypes' (C:\Users\javit\Desktop\Python\myenv\lib\site-packages\noisepy\seis\datatypes.py)_
I have solved this problem by changing the _datatypes.py_ script to the one with the same name which is on GitHub at _NoisePy/src/noisepy/seis/datatypes.py_
But I have a second problem that I can't solve. The problem appears when executing the _cross_correlate(raw_store, config, cc_store)_ command. The error message is as follows 
_1668 ERROR correlate.save(): Error saving CI.BBR and CI.BBR for 2002-01-01T00:00:00+0000 - 2002-01-02T00:00:00+0000: No conversion path for dtype: dtype('<U5')_
This happens with all pairs of stations.
So I can't continue from this point.

Thank you very much for your help.

**Comment by carlosgjs** [comment]
Hello @Javitsg - This is indeed a problem with the latest version of the tutorial. We are working on a fix and will be putting out a new NoisePy release today to address it.

**Comment by Javitsg** [comment]
Thabk you very much!

**Comment by carlosgjs** [comment]
@Javitsg  - We just released noisepy-seis 0.9.82, which addresses these two problems.

**Comment by Javitsg** [comment]
Now it works perfectly. Thank you very much.
