### ISSUE TITLE
Remove Redundant Functions Copied to noisepy-seis-io from noisepy noise_module.py

### ISSUE THREAD

**Issue by IshikaKhandelwal** [noisepy/NoisePy#280]
With the upcoming integration of `noisepy-seis-io`, the functions listed below copied from `noise_module.py`, will no longer needed and should be deleted once noisepy starts consuming noisepy-seis-io.
1) sta_info_from_inv
2) stats2inv_mseed
These functions were initially copied for temporary compatibility reasons but can now be safely removed.

**Comment by IshikaKhandelwal** [comment]
Addressed at https://github.com/noisepy/noisepy-io/pull/5

**Comment by carlosgjs** [comment]
@IshikaKhandelwal the functions that got added to `noisepy-io` need to be removed from `noisepy` to avoid duplication
