### ISSUE TITLE
Creating ASDF files with all the required attributes

### ISSUE THREAD

**Issue by SeismoFelix** [noisepy/NoisePy#324]
After running successfully two of the examples you provided: [noisepy_monitoring_demo](https://seisscoped.org/HPS-book/chapters/noise/noisepy_monitoring_demo.html) and [monitoring_methods_tutorial](https://github.com/noisepy/NoisePy/blob/6a219e537e7f0c0d256574a2b3417a7fa72dfc2c/tutorials/monitoring/monitoring_methods_tutorial.ipynb#L4), I started the journey using local data. I have a collection of continuous data in miniseed. I converted the data into ASDF format, with the following code:

```
miniseed_path = "/Users/felix/Documents/GROUNDWATER_KENTUCKY/KY_GROUNDWATER/ProjectShare/Data/2024_NodeTests/Broadband/2024/08/*.miniseed"
output_asdf_path = "KY_output_data.h5"

st = read(miniseed_path)

ds = ASDFDataSet(output_asdf_path)

for tr in st:
    net = tr.stats.network
    sta = tr.stats.station
    loc = tr.stats.location
    chan = tr.stats.channel
    starttime = tr.stats.starttime
    endtime = tr.stats.endtime
    
    # Add trace to ASDF file
    ds.add_waveforms(tr, tag="raw_recording", event_id=None)
    
print(ds)
```
Then, after setting up the configuration I tried to run a cross-correlation:
cross_correlate(ds, config, cc_store)

And I got this error message:

> AttributeError: 'ASDFDataSet' object has no attribute 'get_timespans'

I wonder if you have any idea about how the ASDF file you use incorporates that attribute into the object. 
Your old documentation refers to a **S0B_to_ASDF.py** script for making this process, but I cannot find it and I assume is not longer valid. 

Your data object looks like this:

> <noisepy.seis.io.s3store.SCEDCS3DataStore object at 0x132da50f0>

 While mine ASDF file looks like:

> ASDF file [format version: 1.0.3]: 'KY_output_data.h5' (1.4 GB)
> 	Contains 0 event(s)
> 	Contains waveform data from 4 station(s).

and it does not contain any attribute  'get_timespans' which is the origin of the error. 

Thanks in advance for all your help.

**Comment by doub1emint** [comment]
Hi Felix! You misnamed the h5 file. Please see lines 79-83 of asdfstore.py. your h5 file name should contain the timerange info like the comments of class ASDFRawDataStore.

https://github.com/noisepy/noisepy-io/blob/76ee9ffc1aae3e5ca1080ff41853ac3b6880e3dc/src/noisepy/seis/io/asdfstore.py#L79-L85

Xingye

**Comment by SeismoFelix** [comment]
Thanks @doub1emint. Now, the issue seems to be the how ASDFRawDataStore retrieves the [channels from the ASDF files](https://github.com/noisepy/noisepy-io/blob/76ee9ffc1aae3e5ca1080ff41853ac3b6880e3dc/src/noisepy/seis/io/asdfstore.py#L89-L97). The channels seem to be retrieved from the tag attribute. However, if a try to put the channel in the tag I got this error from PYASDF:

> ValueError: Invalid tag: 'HHE' - Must satisfy the regex '^[a-z_0-9]+$'.

```
from obspy import read, read_inventory
from pyasdf import ASDFDataSet

# Paths to your data
miniseed_path = "/Users/felix/Documents/GROUNDWATER_KENTUCKY/noisepy/DEMO_DV_V/DATA_TEST/*.miniseed"
output_asdf_path = "ASDF_files/2024_08_24_00_00_00T2024_08_24_23_59_59.h5"
xml_file_path = "/Users/felix/Documents/GROUNDWATER_KENTUCKY/noisepy/DEMO_DV_V/XML_FILES/KY.MSU1_20240821T195433Z.xml"

# Read the MiniSEED data using ObsPy
st = read(miniseed_path)

# Create an ASDF file to store the data (opens in write mode)
ds = ASDFDataSet(output_asdf_path, mode="w")

# Add each trace from the stream to the ASDF dataset
for tr in st:
    net = tr.stats.network
    sta = tr.stats.station
    loc = tr.stats.location
    chan = tr.stats.channel
    starttime = tr.stats.starttime
    endtime = tr.stats.endtime
    
    # Use the channel name as the tag to match NoisePy's expectations
    tag = chan.lower()  # Use the channel code like 'BHZ' or 'HHZ_00' as the tag
    
    # Add trace to ASDF file with the channel as the tag
    ds.add_waveforms(tr, tag=tag, event_id=None)
    print(f"Added trace: {net}.{sta}.{chan} from {starttime} to {endtime}")

# Read the StationXML inventory
inventory = read_inventory(xml_file_path)

# Add the StationXML to the ASDF file
ds.add_stationxml(inventory)
print(f"StationXML added from {xml_file_path} to {output_asdf_path}")

```

It looks like  tag attribute  does not like uppercase letters. 

So if I fix that part I can create the object raw_store:

```
asdf_dir = '/Users/felix/Documents/GROUNDWATER_KENTUCKY/noisepy/DEMO_DV_V/ASDF_files'
raw_store = ASDFRawDataStore(asdf_dir, mode='r')
print(raw_store)
ts=raw_store.get_timespans()
print(ts)
all_channels = raw_store.get_channels(ts[0])
print(all_channels)
```

> <noisepy.seis.io.asdfstore.ASDFRawDataStore object at 0x131b442b0>
[2024-08-24T00:00:00+0000 - 2024-08-24T23:59:59+0000]
[KY.MSU1.hhe, KY.MSU1.hhn, KY.MSU1.hhz]

But, the subroutine cross_correlate cannot find the traces when the channels are named in lowercase. 

<img width="1562" alt="Screenshot 2024-10-18 at 8 56 48 PM" src="https://github.com/user-attachments/assets/390d6c4a-8603-445d-b932-db5f231545f9">

I will keep digging and will keep you posted. 

Thanks!

**Comment by SeismoFelix** [comment]
Since apparently I cannot add uppercase to the tags in PYASDF, I saved the channeI in lowercase in the ASDF file and did this small modification to [asdfstore](https://github.com/noisepy/noisepy-io/blob/76ee9ffc1aae3e5ca1080ff41853ac3b6880e3dc/src/noisepy/seis/io/asdfstore.py#L89-L97)  
```

            channels = [
                Channel(ChannelType(tag.upper()), sta)
                for sta in stations
                for tag in ds.waveforms[str(sta)].get_waveform_tags()
            ]
            return channels
```

So, as soon as it is retrieved the tag, it is changed to uppercase. 

The raw_store object looks like the example you provided:

<img width="769" alt="Screenshot 2024-10-18 at 9 27 54 PM" src="https://github.com/user-attachments/assets/f8d55be5-2fd3-4d64-ba77-a745b3c2e0ee">

But, I still cannot run the cross-correlation. The subroutine  _filter_channel_data in correlate.py yields and empty set when tries to filter the data by sample frequency. 


<img width="1872" alt="Screenshot 2024-10-18 at 9 31 37 PM" src="https://github.com/user-attachments/assets/ecec3e7d-f155-4b5f-91c1-1f927402ad97">

However, the ASDF file I created, stores correctly the sampling rate:

<img width="1080" alt="Screenshot 2024-10-18 at 9 32 07 PM" src="https://github.com/user-attachments/assets/475d9617-1170-4def-aa4e-8643e8262835">

Thanks and sorry if this is overwhelming for you.

**Comment by doub1emint** [comment]
Hi Felix! Sorry about that. I haven't encountered this problem.

**Comment by SeismoFelix** [comment]
Thanks @doub1emint! It worked finally. 

![Screenshot 2024-11-07 at 10 53 28 AM](https://github.com/user-attachments/assets/0f5b9b3d-d34a-4443-87ab-ea064b638315)

The problem was the trace was too short (1 day). Problably I need to adjust of the default parameters  on the example for making it work with short traces. I would like to summarize what the issues I found and how I handled them  in case other users face similar challenges:

**Creating ASDF files from miniseed for performing cross-correlations in NoisePy**

I modified the [NoisePy tutorial ](https://seisscoped.org/HPS-book/chapters/noise/noisepy_monitoring_demo.html) for reading miniseed data, converting into ASDF files and proceed with the cross-correlations. 

You need to provide 3 paths for the miniseed files, the ASDF file to be created and the xml files with the station's metadata. 

```
from obspy import read, read_inventory
from pyasdf import ASDFDataSet

# Paths to your data
miniseed_path = "/Users/felix/Documents/GROUNDWATER_KENTUCKY/noisepy/DEMO_DV_V/DATA_TEST/*.miniseed"
output_asdf_path = "ASDF_files/2024_08_22_00_00_00T2024_08_28_00_00_00.h5"
xml_file_path = "/Users/felix/Documents/GROUNDWATER_KENTUCKY/noisepy/DEMO_DV_V/XML_FILES/KY.MSU1_20240821T195433Z.xml"

# Read the MiniSEED data using ObsPy
st = read(miniseed_path)

# Create an ASDF file to store the data (opens in write mode)
ds = ASDFDataSet(output_asdf_path, mode="w")

# Add each trace from the stream to the ASDF dataset
for tr in st:
    net = tr.stats.network
    sta = tr.stats.station
    loc = tr.stats.location
    chan = tr.stats.channel
    starttime = tr.stats.starttime
    endtime = tr.stats.endtime
    
    # Use the channel name as the tag to match NoisePy's expectations
    tag = chan.lower()  # Use the channel code like 'BHZ' or 'HHZ_00' as the tag
    
    # Add trace to ASDF file with the channel as the tag
    ds.add_waveforms(tr, tag=tag, event_id=None)
    print(f"Added trace: {net}.{sta}.{chan} from {starttime} to {endtime}")

# Read the StationXML inventory
inventory = read_inventory(xml_file_path)

# Add the StationXML to the ASDF file
ds.add_stationxml(inventory)
print(f"StationXML added from {xml_file_path} to {output_asdf_path}")

# Optionally: Print a summary of the ASDF dataset
print(ds)
```
When reading the ASDF files, [NoisePy retrieves the channel information from the tag attribute in the ASDF file](https://github.com/noisepy/noisepy-io/blob/76ee9ffc1aae3e5ca1080ff41853ac3b6880e3dc/src/noisepy/seis/io/asdfstore.py#L89-L97). However, this attribute does not accept capital letters, so it is important to fill the tag attribute with lowercase:

> chan = tr.stats.chann ->  tag = chan.lower()

I also have problems with discrepancies in the number of samples in the trace and the expected ones in the time chunk when dealing with one day traces in the ASDF format. I simply added more time to the ASDF file (27 days ASDF trace rather than one day). However, I believe that adjusting some of the parametres that comes in the example, I can make it work with 1 day traces.

**Comment by doub1emint** [comment]
Congrats! Thanks for sharing your idea.
