### ISSUE TITLE
How to download the data from multiple FDSN clients?

### ISSUE THREAD

**Issue by LevCarlo** [noisepy/NoisePy#328]
How to download the data from multiple FDSN clients? The `ConfigParameters().client_url_key` seems not to support the list input.

**Comment by niyiyu** [comment]
Hi @LevCarlo, this argument is actually passed to `obspy.clients.fdsn.Client()`, which doesn't support multiple argument. A network code could be hosted by multiple data center, which creates ambiguities. So I would recommend you to download separately if the data you want is hosted by different data center.
